package com.popupmc.skyfall;

import org.bukkit.Material;

public class BreathableBlocks {
    // Checks if the material is breathable
    public static boolean isBreathable(Material material) {
        return material.isAir() ||
                material == Material.LADDER ||
                material == Material.WATER ||
                material == Material.VINE ||
                material == Material.POWERED_RAIL ||
                material == Material.DETECTOR_RAIL ||
                material == Material.COBWEB ||
                material == Material.GRASS ||
                material == Material.FERN ||
                material == Material.DEAD_BUSH ||
                material == Material.SEAGRASS ||
                material == Material.SEA_PICKLE ||
                material == Material.DANDELION ||
                material == Material.POPPY ||
                material == Material.BLUE_ORCHID ||
                material == Material.ALLIUM ||
                material == Material.AZURE_BLUET ||
                material == Material.RED_TULIP ||
                material == Material.ORANGE_TULIP ||
                material == Material.WHITE_TULIP ||
                material == Material.PINK_TULIP ||
                material == Material.OXEYE_DAISY ||
                material == Material.CORNFLOWER ||
                material == Material.LILY_OF_THE_VALLEY ||
                material == Material.BROWN_MUSHROOM ||
                material == Material.RED_MUSHROOM ||
                material == Material.OAK_SLAB ||
                material == Material.SPRUCE_SLAB ||
                material == Material.BIRCH_SLAB ||
                material == Material.JUNGLE_SLAB ||
                material == Material.ACACIA_SLAB ||
                material == Material.DARK_OAK_SLAB ||
                material == Material.STONE_SLAB ||
                material == Material.SMOOTH_STONE_SLAB ||
                material == Material.SANDSTONE_SLAB ||
                material == Material.CUT_SANDSTONE_SLAB ||
                material == Material.PETRIFIED_OAK_SLAB ||
                material == Material.COBBLESTONE_SLAB ||
                material == Material.BRICK_SLAB ||
                material == Material.STONE_BRICK_SLAB ||
                material == Material.NETHER_BRICK_SLAB ||
                material == Material.QUARTZ_SLAB ||
                material == Material.RED_SANDSTONE_SLAB ||
                material == Material.CUT_RED_SANDSTONE_SLAB ||
                material == Material.PURPUR_SLAB ||
                material == Material.PRISMARINE_SLAB ||
                material == Material.PRISMARINE_BRICK_SLAB ||
                material == Material.DARK_PRISMARINE_SLAB ||
                material == Material.TORCH ||
                material == Material.WALL_TORCH ||
                material == Material.RAIL ||
                material == Material.LEVER ||
                material == Material.STONE_PRESSURE_PLATE ||
                material == Material.OAK_PRESSURE_PLATE ||
                material == Material.SPRUCE_PRESSURE_PLATE ||
                material == Material.BIRCH_PRESSURE_PLATE ||
                material == Material.JUNGLE_PRESSURE_PLATE ||
                material == Material.ACACIA_PRESSURE_PLATE ||
                material == Material.DARK_OAK_PRESSURE_PLATE ||
                material == Material.REDSTONE_TORCH ||
                material == Material.STONE_BUTTON ||
                material == Material.SNOW ||
                material == Material.OAK_TRAPDOOR ||
                material == Material.SPRUCE_TRAPDOOR ||
                material == Material.BIRCH_TRAPDOOR ||
                material == Material.JUNGLE_TRAPDOOR ||
                material == Material.ACACIA_TRAPDOOR ||
                material == Material.DARK_OAK_TRAPDOOR ||
                material == Material.LILY_PAD ||
                material == Material.TRIPWIRE_HOOK ||
                material == Material.TRIPWIRE ||
                material == Material.OAK_BUTTON ||
                material == Material.SPRUCE_BUTTON ||
                material == Material.BIRCH_BUTTON ||
                material == Material.JUNGLE_BUTTON ||
                material == Material.ACACIA_BUTTON ||
                material == Material.DARK_OAK_BUTTON ||
                material == Material.LIGHT_WEIGHTED_PRESSURE_PLATE ||
                material == Material.HEAVY_WEIGHTED_PRESSURE_PLATE ||
                material == Material.DAYLIGHT_DETECTOR ||
                material == Material.ACTIVATOR_RAIL ||
                material == Material.IRON_TRAPDOOR ||
                material == Material.WHITE_CARPET ||
                material == Material.ORANGE_CARPET ||
                material == Material.MAGENTA_CARPET ||
                material == Material.LIGHT_BLUE_CARPET ||
                material == Material.YELLOW_CARPET ||
                material == Material.LIME_CARPET ||
                material == Material.PINK_CARPET ||
                material == Material.GRAY_CARPET ||
                material == Material.LIGHT_GRAY_CARPET ||
                material == Material.CYAN_CARPET ||
                material == Material.PURPLE_CARPET ||
                material == Material.BLUE_CARPET ||
                material == Material.BROWN_CARPET ||
                material == Material.GREEN_CARPET ||
                material == Material.RED_CARPET ||
                material == Material.BLACK_CARPET ||
                material == Material.SUNFLOWER ||
                material == Material.LILAC ||
                material == Material.PEONY ||
                material == Material.BUBBLE_COLUMN ||
                material == Material.TALL_GRASS ||
                material == Material.LARGE_FERN ||
                material == Material.TUBE_CORAL ||
                material == Material.BRAIN_CORAL ||
                material == Material.BUBBLE_CORAL ||
                material == Material.FIRE_CORAL ||
                material == Material.HORN_CORAL ||
                material == Material.DEAD_TUBE_CORAL ||
                material == Material.DEAD_BRAIN_CORAL ||
                material == Material.DEAD_BUBBLE_CORAL ||
                material == Material.DEAD_FIRE_CORAL ||
                material == Material.DEAD_HORN_CORAL ||
                material == Material.TUBE_CORAL_FAN ||
                material == Material.BRAIN_CORAL_FAN ||
                material == Material.BUBBLE_CORAL_FAN ||
                material == Material.FIRE_CORAL_FAN ||
                material == Material.HORN_CORAL_FAN ||
                material == Material.DEAD_TUBE_CORAL_FAN ||
                material == Material.DEAD_BRAIN_CORAL_FAN ||
                material == Material.DEAD_BUBBLE_CORAL_FAN ||
                material == Material.DEAD_FIRE_CORAL_FAN ||
                material == Material.DEAD_HORN_CORAL_FAN ||
                material == Material.TUBE_CORAL_WALL_FAN ||
                material == Material.BRAIN_CORAL_WALL_FAN ||
                material == Material.BUBBLE_CORAL_WALL_FAN ||
                material == Material.FIRE_CORAL_WALL_FAN ||
                material == Material.HORN_CORAL_WALL_FAN ||
                material == Material.DEAD_TUBE_CORAL_WALL_FAN ||
                material == Material.DEAD_BRAIN_CORAL_WALL_FAN ||
                material == Material.DEAD_BUBBLE_CORAL_WALL_FAN ||
                material == Material.DEAD_FIRE_CORAL_WALL_FAN ||
                material == Material.DEAD_HORN_CORAL_WALL_FAN ||
                material == Material.POLISHED_GRANITE_SLAB ||
                material == Material.SMOOTH_RED_SANDSTONE_SLAB ||
                material == Material.MOSSY_STONE_BRICK_SLAB ||
                material == Material.POLISHED_DIORITE_SLAB ||
                material == Material.MOSSY_COBBLESTONE_SLAB ||
                material == Material.END_STONE_BRICK_SLAB ||
                material == Material.SMOOTH_SANDSTONE_SLAB ||
                material == Material.SMOOTH_QUARTZ_SLAB ||
                material == Material.GRANITE_SLAB ||
                material == Material.ANDESITE_SLAB ||
                material == Material.RED_NETHER_BRICK_SLAB ||
                material == Material.POLISHED_ANDESITE_SLAB ||
                material == Material.DIORITE_SLAB ||
                material == Material.SCAFFOLDING ||
                material == Material.IRON_DOOR ||
                material == Material.OAK_DOOR ||
                material == Material.SPRUCE_DOOR ||
                material == Material.BIRCH_DOOR ||
                material == Material.JUNGLE_DOOR ||
                material == Material.ACACIA_DOOR ||
                material == Material.DARK_OAK_DOOR ||
                material == Material.REPEATER ||
                material == Material.COMPARATOR ||
                material == Material.PAINTING ||
                material == Material.OAK_SIGN ||
                material == Material.SPRUCE_SIGN ||
                material == Material.BIRCH_SIGN ||
                material == Material.JUNGLE_SIGN ||
                material == Material.ACACIA_SIGN ||
                material == Material.DARK_OAK_SIGN ||
                material == Material.OAK_WALL_SIGN ||
                material == Material.SPRUCE_WALL_SIGN ||
                material == Material.BIRCH_WALL_SIGN ||
                material == Material.JUNGLE_WALL_SIGN ||
                material == Material.ACACIA_WALL_SIGN ||
                material == Material.DARK_OAK_WALL_SIGN ||
                material == Material.MINECART ||
                material == Material.OAK_BOAT ||
                material == Material.KELP_PLANT ||
                material == Material.SUGAR_CANE ||
                material == Material.BAMBOO ||
                material == Material.CHEST_MINECART ||
                material == Material.FURNACE_MINECART ||
                material == Material.ITEM_FRAME ||
                material == Material.BREWING_STAND ||
                material == Material.CAULDRON ||
                material == Material.FLOWER_POT ||
                material == Material.WITHER_ROSE ||
                material == Material.SKELETON_SKULL ||
                material == Material.WITHER_SKELETON_SKULL ||
                material == Material.PLAYER_HEAD ||
                material == Material.ZOMBIE_HEAD ||
                material == Material.CREEPER_HEAD ||
                material == Material.DRAGON_HEAD ||
                material == Material.SKELETON_WALL_SKULL ||
                material == Material.WITHER_SKELETON_WALL_SKULL ||
                material == Material.PLAYER_WALL_HEAD ||
                material == Material.ZOMBIE_WALL_HEAD ||
                material == Material.CREEPER_WALL_HEAD ||
                material == Material.DRAGON_WALL_HEAD ||
                material == Material.TNT_MINECART ||
                material == Material.HOPPER_MINECART ||
                material == Material.ARMOR_STAND ||
                material == Material.LEAD ||
                material == Material.WHITE_BANNER ||
                material == Material.ORANGE_BANNER ||
                material == Material.MAGENTA_BANNER ||
                material == Material.LIGHT_BLUE_BANNER ||
                material == Material.YELLOW_BANNER ||
                material == Material.LIME_BANNER ||
                material == Material.PINK_BANNER ||
                material == Material.GRAY_BANNER ||
                material == Material.LIGHT_GRAY_BANNER ||
                material == Material.CYAN_BANNER ||
                material == Material.PURPLE_BANNER ||
                material == Material.BLUE_BANNER ||
                material == Material.BROWN_BANNER ||
                material == Material.GREEN_BANNER ||
                material == Material.RED_BANNER ||
                material == Material.BLACK_BANNER ||
                material == Material.WHITE_WALL_BANNER ||
                material == Material.ORANGE_WALL_BANNER ||
                material == Material.MAGENTA_WALL_BANNER ||
                material == Material.LIGHT_BLUE_WALL_BANNER ||
                material == Material.YELLOW_WALL_BANNER ||
                material == Material.LIME_WALL_BANNER ||
                material == Material.PINK_WALL_BANNER ||
                material == Material.GRAY_WALL_BANNER ||
                material == Material.LIGHT_GRAY_WALL_BANNER ||
                material == Material.CYAN_WALL_BANNER ||
                material == Material.PURPLE_WALL_BANNER ||
                material == Material.BLUE_WALL_BANNER ||
                material == Material.BROWN_WALL_BANNER ||
                material == Material.GREEN_WALL_BANNER ||
                material == Material.RED_WALL_BANNER ||
                material == Material.BLACK_WALL_BANNER ||
                material == Material.END_CRYSTAL ||
                material == Material.BEETROOT_SEEDS ||
                material == Material.SPRUCE_BOAT ||
                material == Material.BIRCH_BOAT ||
                material == Material.JUNGLE_BOAT ||
                material == Material.ACACIA_BOAT ||
                material == Material.DARK_OAK_BOAT ||
                material == Material.GRINDSTONE ||
                material == Material.LECTERN ||
                material == Material.STONECUTTER ||
                material == Material.BELL ||
                material == Material.LANTERN ||
                material == Material.CHAIN ||
                material == Material.CRIMSON_ROOTS ||
                material == Material.WARPED_ROOTS ||
                material == Material.NETHER_SPROUTS ||
                material == Material.SOUL_CAMPFIRE ||
                material == Material.SOUL_FIRE ||
                material == Material.SOUL_LANTERN ||
                material == Material.SOUL_TORCH ||
                material == Material.SOUL_WALL_TORCH ||
                material == Material.TWISTING_VINES ||
                material == Material.TWISTING_VINES_PLANT ||
                material == Material.WEEPING_VINES ||
                material == Material.WEEPING_VINES_PLANT ||
                material == Material.CRIMSON_FUNGUS ||
                material == Material.CRIMSON_SLAB ||
                material == Material.CRIMSON_PRESSURE_PLATE ||
                material == Material.CRIMSON_FENCE ||
                material == Material.CRIMSON_TRAPDOOR ||
                material == Material.CRIMSON_FENCE_GATE ||
                material == Material.CRIMSON_STAIRS ||
                material == Material.CRIMSON_BUTTON ||
                material == Material.CRIMSON_DOOR ||
                material == Material.CRIMSON_SIGN ||
                material == Material.POTTED_WARPED_ROOTS ||
                material == Material.WARPED_FUNGUS ||
                material == Material.WARPED_SLAB ||
                material == Material.WARPED_PRESSURE_PLATE ||
                material == Material.WARPED_FENCE ||
                material == Material.WARPED_TRAPDOOR ||
                material == Material.WARPED_FENCE_GATE ||
                material == Material.WARPED_STAIRS ||
                material == Material.WARPED_BUTTON ||
                material == Material.WARPED_DOOR ||
                material == Material.WARPED_SIGN;
    }
}
